import Image from "@/components/ui/site-image";
import Link from "next/link";
import {ArrowUpRight,Wheat,MapPin,FileText,UserRound,Check,Star} from "lucide-react";
import {aboutCopy,ruralCopy,areas,steps,site,testimonials} from "@/lib/site";
import {ArrowButton} from "./ui/arrow-button";
import {Reveal} from "./ui/reveal";
import {CoverflowCarousel} from "./ui/coverflow-carousel";
import {InfoMarquee} from "./ui/info-marquee";
import {ProfileCarousel} from "./ui/profile-carousel";
export function About(){return <section className="section wrap about-grid"><ProfileCarousel/><Reveal><span className="eyebrow">MARIA RONIKERLLY MELO</span><h2>Experiência previdenciária com olhar atento à realidade de cada cliente.</h2><p>{aboutCopy}</p><p>Com atuação em <strong>Araripina e região</strong>, valoriza um atendimento baseado em proximidade, responsabilidade e confiança.</p><Link className="text-link" href="/sobre">Conheça minha forma de atuação <ArrowUpRight size={18}/></Link></Reveal></section>}
export function Rural(){return <section className="rural-section"><div className="wrap rural-grid"><Reveal><span className="eyebrow">ESPECIALIDADE</span><h2>Especialista em<br/><em>Benefícios Rurais</em></h2><Wheat className="rural-wheat" strokeWidth={1}/><p className="editorial-quote">Quem vive do campo tem uma história de trabalho que precisa ser corretamente demonstrada.</p></Reveal><Reveal><p>{ruralCopy}</p><p>Uma análise individual permite organizar as informações relevantes, compreender os requisitos aplicáveis e definir o caminho jurídico adequado para cada situação.</p><ul className="support-list">{["Análise individual do caso","Atenção à documentação","Orientação previdenciária clara","Conhecimento das particularidades da atividade rural"].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><ArrowButton light href="/beneficios-rurais">Entender melhor os benefícios rurais</ArrowButton></Reveal></div></section>}
export function Areas(){return <section className="section areas-section"><div className="wrap section-heading"><div><span className="eyebrow">ATUAÇÃO JURÍDICA</span><h2>Áreas de atuação previdenciária</h2></div><p>Atuação voltada à análise e orientação em demandas previdenciárias, sempre considerando as particularidades de cada caso.</p></div><CoverflowCarousel slides={areas.filter(a=>a.enabled).map(a=>({src:a.image,alt:a.alt,title:a.title,subtitle:a.description,href:a.href,badge:a.specialty?"ESPECIALIDADE DO ESCRITÓRIO":undefined}))} interval={1500}/></section>}
export function AreaDetails(){return <section className="section wrap area-details"><span className="eyebrow">ORIENTAÇÃO INDIVIDUALIZADA</span><h2>Conheça cada área de atuação</h2>{areas.filter(a=>a.enabled).map(a=><Reveal key={a.id}><article id={a.id} className="area-detail"><div className="area-detail-image"><Image src={a.image} alt={a.alt} fill sizes="(max-width: 700px) 100vw, 300px"/></div><div>{a.specialty&&<span className="eyebrow">ESPECIALIDADE DO ESCRITÓRIO</span>}<h3>{a.title}</h3><p>{a.fullDescription}</p><ArrowButton href={a.specialty?"/beneficios-rurais":"/contato"}>{a.specialty?"Conhecer benefícios rurais":"Falar com uma advogada"}</ArrowButton></div></article></Reveal>)}</section>}
export function Process(){return <section className="process section"><div className="wrap"><span className="eyebrow">PASSO A PASSO</span><h2>Um atendimento claro do início ao fim</h2><div className="steps">{steps.map(([title,text],i)=><Reveal key={title} className="step"><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>}
export function Reviews(){if(!site.reviewsEnabled||!testimonials.length)return null;return <section className="section wrap"><h2>A confiança de quem já foi atendido</h2><div className="reviews">{[0,1,2].map(col=><div className="review-column" key={col} style={{animationDuration:`${[15,19,17][col]}s`}}>{testimonials.filter((_,i)=>i%3===col).map(t=><blockquote key={t.name}><p>{t.text}</p><footer>{t.name}</footer>{t.rating&&<span aria-label={`${t.rating} estrelas`}>{Array.from({length:t.rating},(_,i)=><Star size={16} key={i}/>)}</span>}{t.source==="google"&&<small>Avaliação do Google</small>}</blockquote>)}</div>)}</div></section>}
export function FinalCTA(){return <section className="final-cta"><div className="cta-photo"><Image src="/images/maria-ronikerlly-office-seated.jpeg" alt="Maria Ronikerlly Melo em seu escritório, sentada em uma poltrona" fill sizes="(max-width: 700px) 100vw, 40vw"/></div><div className="cta-content"><span className="eyebrow">VAMOS CONVERSAR</span><h2>Precisa de orientação sobre seus direitos previdenciários?</h2><p>Cada situação possui particularidades. Entre em contato para compreender melhor o seu caso e receber uma orientação sobre os próximos passos possíveis.</p><ArrowButton/><div className="cta-note">Advocacia Previdenciária · Especialista em Benefícios Rurais<br/>Araripina e Região</div></div></section>}
export function MicroDetails(){return <InfoMarquee/>}
export function Principles(){return <section className="section wrap"><span className="eyebrow">PRINCÍPIOS DO ATENDIMENTO</span><h2>Clareza, proximidade e responsabilidade.</h2><div className="principles">{[[UserRound,"Escuta cuidadosa","Cada trajetória merece ser compreendida antes de definir os próximos passos."],[FileText,"Análise individual","A documentação e as particularidades do caso orientam a atuação."],[MapPin,"Proximidade","Atuação em Araripina e região, com atenção à realidade de cada cliente."]].map(([Icon,title,text])=>{const I=Icon as typeof UserRound;return <div key={String(title)}><I strokeWidth={1.3}/><h3>{String(title)}</h3><p>{String(text)}</p></div>})}</div></section>}
