import Image from "@/components/ui/site-image";
import Link from "next/link";
import {notFound} from "next/navigation";
import {posts} from "@/content/blog/posts";
import {site} from "@/lib/site";
import {pageMeta} from "@/lib/seo";
import {Breadcrumbs} from "@/components/breadcrumbs";
import {BlogSection} from "@/components/blog";
import {ArrowButton} from "@/components/ui/arrow-button";
export const dynamicParams=false;
export function generateStaticParams(){return posts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=posts.find(p=>p.slug===slug);if(!post)return {};return {...pageMeta(post.title,post.excerpt,`/blog/${post.slug}`),robots:{index:!post.draft&&site.publicReleaseApproved,follow:true},openGraph:{type:"article" as const,title:post.title,description:post.excerpt,url:site.origin+`/blog/${post.slug}`,publishedTime:post.publishedAt,images:[{url:site.origin+post.coverImage,alt:post.coverAlt}]}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=posts.find(p=>p.slug===slug);if(!post)notFound();return <><Breadcrumbs items={[{label:"Blog",href:"/blog"},{label:post.title,href:`/blog/${post.slug}`}]}/><article className="article wrap"><span className="eyebrow">{post.category}</span><h1>{post.title}</h1><div className="article-meta">{post.draft?"Rascunho editorial · Revisão jurídica pendente":"Por "+post.author} · <time dateTime={post.publishedAt}>{new Date(post.publishedAt+"T12:00:00Z").toLocaleDateString("pt-BR",{timeZone:"UTC"})}</time>{post.updatedAt&&<> · Atualizado em <time dateTime={post.updatedAt}>{post.updatedAt}</time></>}</div><p>{post.excerpt}</p><div className="article-cover"><Image src={post.coverImage} alt={post.coverAlt} fill sizes="(max-width: 800px) 100vw, 800px"/></div>{post.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2><p>{s.text}</p></section>)}<h2>Continue se informando</h2><p><Link href="/beneficios-rurais">Conheça a atuação em Benefícios Rurais</Link> e veja também <Link href={`/blog/${post.slug==="documentos-atividade-rural"?"segurado-especial":"documentos-atividade-rural"}`}>como organizar a análise da atividade rural</Link>.</p><h2>Fontes oficiais</h2><ul>{post.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.label} ↗</a></li>)}</ul><p className="editorial-notice">Conteúdo informativo. Não substitui a análise individual do caso e não representa promessa de resultado.{post.draft&&" Texto preparado para revisão antes da publicação pública; autoria e revisão profissional ainda não confirmadas."}</p><div className="author-card"><Image src="/images/maria-ronikerlly-portrait-beige.jpeg" width={70} height={70} alt="Maria Ronikerlly Melo"/><div><strong>Maria Ronikerlly Melo</strong><p>Advogada Previdenciária · Especialista em Benefícios Rurais</p>{post.reviewer==="TODO_CONFIRMAR"&&<p>Revisão deste artigo pendente.</p>}<Link href="/sobre">Conheça a advogada</Link></div></div><h2>Precisa compreender melhor o seu caso?</h2><p>Apresente sua situação para receber orientação sobre os próximos passos possíveis.</p><ArrowButton/></article><BlogSection related exclude={post.slug}/>{!post.draft&&post.author!=="TODO_CONFIRMAR"&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.excerpt,image:site.origin+post.coverImage,datePublished:post.publishedAt,dateModified:post.updatedAt||post.publishedAt,author:{"@type":"Person",name:post.author,url:site.origin+"/sobre"},mainEntityOfPage:site.origin+"/blog/"+post.slug}).replace(/</g,"\u003c")}}/>}</>}
